set(RENDER_SHADER_DIR ${CMAKE_CURRENT_SOURCE_DIR}/src/render/shaders)
set(RENDER_SHADER_EMBED
    overlay.hlsl:Overlay
)
set(RENDER_SHADER_FILES "")
set(GENERATED_SHADER_HEADER ${CMAKE_CURRENT_BINARY_DIR}/src/render/shader_sources.h)
foreach(RENDER_SHADER_ENTRY ${RENDER_SHADER_EMBED})
    string(REPLACE ":" ";" RENDER_SHADER_PAIR ${RENDER_SHADER_ENTRY})
    list(GET RENDER_SHADER_PAIR 0 RENDER_SHADER_FILE)
    list(APPEND RENDER_SHADER_FILES ${RENDER_SHADER_DIR}/${RENDER_SHADER_FILE})
endforeach()
add_custom_command(
    OUTPUT ${GENERATED_SHADER_HEADER}
    COMMAND ${CMAKE_COMMAND}
        -DSHADER_DIR=${RENDER_SHADER_DIR}
        -DOUTPUT_HEADER=${GENERATED_SHADER_HEADER}
        "-DEMBED_ENTRIES=${RENDER_SHADER_EMBED}"
        -P ${CMAKE_CURRENT_SOURCE_DIR}/cmake/embed_shaders.cmake
    DEPENDS ${RENDER_SHADER_FILES} ${CMAKE_CURRENT_SOURCE_DIR}/cmake/embed_shaders.cmake
    COMMENT "Embedding HLSL sources (render/shaders)"
    VERBATIM
)

